pipeline:
  name: eks_project
  identifier: eks_project
  projectIdentifier: Rajesh_scope
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Github_connector
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: Build_and_Push
        identifier: Build_and_Push
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: Eks_connector
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Find docker file
                  identifier: Find_docker_file
                  spec:
                    connectorRef: Docker_connector
                    image: alpine
                    shell: Sh
                    command: |-
                      find /harness -name "Dockerfile"
                      pwd
                      ls -la
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: Docker_connector
                    repo: rajesh0250/eks-project
                    tags:
                      - master-<+pipeline.sequenceId>
                    caching: true
                    dockerfile: Dockerfile
                    context: .
                    baseImageConnectorRefs:
                      - Docker_connector
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: K8s_service
            gitBranch: main
          environment:
            environmentRef: eksenv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: eksinfra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
