pipeline:
  identifier: Build_Rajesh0250_Zomato_Project_1784167898442
  name: Build Zomato-Project
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: Rajesh0250/Zomato-Project
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Sh
                    command: echo hello world
                  timeout: ""
                  type: Run
          infrastructure:
            type: VM
            spec:
              type: Pool
              spec:
                poolName: pool.yml
                os: Linux
        type: CI
