pipeline:
  identifier: Build_Rajesh0250_Zomato_Project_1784291771402
  name: Build Zomato-Project
  orgIdentifier: default
  projectIdentifier: Rajesh_scope
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: Rajesh0250/Zomato-Project
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Docker
        type: CI
